# Generated by Django 4.2.2 on 2023-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='comentdate',
            field=models.DateTimeField(),
        ),
    ]
