# Generated by Django 4.2.2 on 2023-06-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_date_alter_subpost_comentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subpost',
            name='user',
        ),
    ]
